### ISSUE TITLE
BadDeviceId calling waveOutOpen

### ISSUE THREAD

**Issue by Kenshin210R** [blueskythlikesclouds/SonicAudioTools#16]
[ace_log.txt](https://github.com/blueskythlikesclouds/SonicAudioTools/files/14853156/ace_log.txt)

This is what I get when I try to play the HCA files inside the Dragon Quest Monsters: The Dark Prince ACB/AWB.

**Comment by blueskythlikesclouds** [comment]
I think you are reporting this to the wrong repository, I have no involvement with this "AudioCueEditor" tool mentioned in the logs.

**Comment by Kenshin210R** [comment]
Indeed, sorry for this, I happened to check both repositories at the same time, when I realised it was the wrong one I tried to delete the message but I didn't know how.
