### ISSUE TITLE
acbEditor not working for Sonic Forces

### ISSUE THREAD

**Issue by PotterAndMatrixFan** [blueskythlikesclouds/SonicAudioTools#4]
The acbEditor does not work with Sonic Forces. It doesn't export the files in Windows 10. Pretty please fix this.

**Comment by RadiantDerg** [comment]
Works just fine for me. (commit  **47d082f**)
Are you sure you are dragging an ACB format file onto AcbEditor.exe? Or are you talking about rebuilding?

**Comment by PotterAndMatrixFan** [comment]
Modding the Super Sonic and Shadow DLC's music works just fine, but the rest doesn't. I get an error saying: '@ UTF' signature could not be found. Your file might be corrupted.

It might have to do with quickbms (the 4 gb exe) crashing during export. If it's not too much to ask, maybe I could get a clean sound folder from wars_0.cpk? I've tried to reinstall the game multiple times, but I still get the same error.

**Comment by PotterAndMatrixFan** [comment]
Never mind, I just had to unpack the cpk with VGMToolbox instead of QuickBMS. Works fine now.
