### ISSUE TITLE
CsbEditor: case sensitivity issue.

### ISSUE THREAD

**Issue by OSA413** [blueskythlikesclouds/SonicAudioTools#5]
**Bug description**

CsbEditor doesn't do anything with a CSB file if it ends with ".CSB" instead of ".csb".

**To reproduce**

1. Get any csb file that CsbEditor can extract/reimport.
2. Rename the file extention from ".csb" to ".CSB".
3. Use CsbEditor on the renamed file.

**Expected behavior**

Expected the CSB file to be extracted/reimported.

**Additional context**

Sonic 4's CSB files end with ".CSB".

**Comment by blueskythlikesclouds** [comment]
Yeah, I'm aware of this, just never got around to fix it.
Hold on.

**Comment by blueskythlikesclouds** [comment]
I'm not able to test it but it should most likely work. 04f9952  
I'm closing this now, but if it for some reason doesn't work, be sure to mention.

**Comment by OSA413** [comment]
Hello again!

I've just ran into another issue with case sensitivity.
At this time CsbEditor can't extract a .CSB file that has a .CPK with it.

The program checks if a related `.cpk` file exists `at 49 line of "/Source/CsbEditor/Program.cs"`, but it can't find it because it's actually a `.CPK` file.

**_This problem is exclusive for case-sensitive file systems (e.g. ext3 on Linux)._**

**Comment by OSA413** [comment]
@blueskythlikesclouds 
I'm sorry for pinging you but it seems to me that you haven't received a notification about my previous message.
And there're also issues in the source code that don't allow me to compile the program on Linux without fixing word casing in `.csproj` files. I can fix it and send PR if you don't mind.

**Comment by blueskythlikesclouds** [comment]
Hello.

I don't have a Linux environment so I cannot test this and fix it accordingly. You could fix it yourself and create a PR.
