### ISSUE TITLE
Name Issues

### ISSUE THREAD

**Issue by TraBinary** [blueskythlikesclouds/SonicAudioTools#6]
this tools are great, but not name for files?
files has name, in CueIndex
you can search **CueIndex** word in hex editor (in acb file) and you can see list of names
can you fix name problem? hca files has name and i have to lesson to all of 675 sound effects to find my target effect and mod it. but with names, its really faster to find a special file

**Comment by blueskythlikesclouds** [comment]
You could try using VGMToolbox to extract the ACBs with file names.

These tools are very old (more than 2 years old now,) and I'm obviously not satisfied with them.

I'm soon going to rewrite this solution from scratch and add file name support to ACB Editor. Until then, sorry, I cannot do anything at the moment due to real life stopping me from doing so.

**Comment by TraBinary** [comment]
no dude, i just wanted to find a special name and mod it between alot of files, and just one more important thing: just don't add external folder, just let them be in exported folder with acb contents
acb is just a package, just like cpk, but most of people think it's a file archive with an extra table in game data, but its up to game, right?
so write an importer, not a maker or creator, or create file based on old header
because most of games can read music files with a new archive, so recreating is not a good idea for acb
sorry for my bad english or that i writing so much

just want to add another request: can you work on .usm files? i always using hex editor but it's limited 

Thank you

**Comment by blueskythlikesclouds** [comment]
I don't quite get what you mean.

So what you are saying is, many games don't accept modifications made to the .acb and .awb files because I'm creating a new header for them?

Also for .usm, maybe, but like I mentioned in the previous comment, not at the moment.

**Comment by TraBinary** [comment]
> I don't quite get what you mean.
sorry. i'm not good in talking
just don't recreate files, just import files based on original header (don't create a new file or new header to rebuild acb or awb when you want to rewrite your tool, some games need original template for playing)

**Comment by blueskythlikesclouds** [comment]
Oh, I see.
How come they don't play? Is it possible that you are only testing the .awb file in game? After repacking, .acb is also updated for changes to work.

**Comment by blueskythlikesclouds** [comment]
Closing this as this project has not been maintained for years.
